---
- name: Add the repo to the yum folder
  template:
    src: "{{ rsyslog8_rhel_centos_repo_yum_template }}"
    dest: "{{ rsyslog8_rhel_centos_repo_yum_dest }}"
    owner: "{{ rsyslog8_rhel_centos_repo_yum_owner }}"
    group: "{{ rsyslog8_rhel_centos_repo_yum_group }}"
    mode: "{{ rsyslog8_rhel_centos_repo_yum_mode }}"

- name: Install rsyslog8
  yum:
    name: "{{ rsyslog8_rhel_centos_pkg_name }}"
    enablerepo: "{{ rsyslog8_rhel_centos_repo_yum_repo_id }}"
    state: "{{ 'latest' if rsyslog8_pkg_install_latest else 'present' }}"
    update_cache: "{{ rsyslog8_rhel_centos_update_cache }}"
  notify:
    - restart rsyslog8
...
